const DATABASE = {
  "Marie": {
    "en": {
      "Term 1 Week 2": [
        { w: "ingredients", s: "Mix all the ingredients in a bowl." },
        { w: "clattered", s: "The pans clattered on the floor." },
        { w: "frothy", s: "The coffee was hot and frothy." },
        { w: "canister", s: "Pass me the sugar canister." },
        { w: "novice", s: "He is a novice at chess." },
        { w: "mediocre", s: "The food was only mediocre." },
        { w: "athlete", s: "She is a talented athlete." },
        { w: "illegible", s: "His handwriting is illegible." },
        { w: "gestured", s: "She gestured for us to follow." },
        { w: "raised an eyebrow, looked at me puzzledly and shrugged", s: "She raised an eyebrow, looked at me puzzledly and shrugged." },
        { w: "craned our necks and strained our eyes", s: "We craned our necks and strained our eyes to see." },
        { w: "in hushed tones", s: "They spoke in hushed tones." }
      ],
      "Term 1 Week 3": [
        { w: "acquaintance", s: "He is just an acquaintance." },
        { w: "adequate", s: "The food supply is adequate." },
        { w: "analysis", s: "The analysis of the data is done." },
        { w: "appalling", s: "The weather was appalling." },
        { w: "apparent", s: "It was apparent that he was sad." },
        { w: "appropriate", s: "Wear appropriate clothes." },
        { w: "hurled insults", s: "The angry man hurled insults." },
        { w: "was spoiling for a fight", s: "He was spoiling for a fight." },
        { w: "was boiling with rage", s: "She was boiling with rage." },
        { w: "gritted her teeth", s: "She gritted her teeth in pain." },
        { w: "clenched her fists", s: "He clenched his fists tightly." },
        { w: "cringed in terror", s: "The dog cringed in terror." },
        { w: "rained torrents of abuse", s: "He rained torrents of abuse on them." }
      ],
      "Term 1 Week 4": [
        { w: "veterinarian", s: "The veterinarian treated the dog." },
        { w: "responsibilities", s: "Know your responsibilities." },
        { w: "escalator", s: "Take the escalator up." },
        { w: "preventable", s: "Accidents are preventable." },
        { w: "infections", s: "Clean the wound to stop infections." },
        { w: "pedestrians", s: "Cars must stop for pedestrians." },
        { w: "peculiarly", s: "He behaved peculiarly." },
        { w: "knowledgeable", s: "She is knowledgeable about birds." },
        { w: "psyched up", s: "I am psyched up for the game." },
        { w: "head was spinning with excitement", s: "My head was spinning with excitement." },
        { w: "paralysed with fear", s: "He stood paralysed with fear." },
        { w: "quivering like jelly", s: "She was quivering like jelly." }
      ],
      "Term 1 Week 5": [
        { w: "concentrate", s: "I need to concentrate on my work." },
        { w: "curious", s: "The cat was very curious." },
        { w: "curiosity", s: "Curiosity killed the cat." },
        { w: "decision", s: "Make a good decision." },
        { w: "desperate", s: "He was desperate for water." },
        { w: "deteriorate", s: "The building started to deteriorate." },
        { w: "on cloud nine", s: "She was on cloud nine after winning." },
        { w: "face lit up like sun rays shining down", s: "Her face lit up like sun rays shining down." },
        { w: "heart swelled", s: "My heart swelled with pride." },
        { w: "walked with a spring in her step", s: "She walked with a spring in her step." },
        { w: "broke my heart", s: "It broke my heart to see him cry." },
        { w: "bawled her eyes out", s: "She bawled her eyes out." },
        { w: "lips curled downwards", s: "His lips curled downwards." },
        { w: "tears started rolling down his cheeks", s: "Tears started rolling down his cheeks." }
      ],
      "Term 1 Week 6": [
        { w: "paralysed", s: "His legs were paralysed." },
        { w: "disability", s: "He overcame his disability." },
        { w: "mischievous", s: "The mischievous puppy hid my shoe." },
        { w: "resilience", s: "She showed great resilience." },
        { w: "determination", s: "He worked with determination." },
        { w: "intentional", s: "It was an intentional mistake." },
        { w: "the extra mile", s: "Go the extra mile for success." },
        { w: "went forward to render assistance", s: "He went forward to render assistance." },
        { w: "the knot in her stomach loosened", s: "The knot in her stomach loosened." },
        { w: "heart swelled with pride", s: "His heart swelled with pride." },
        { w: "on the brink of tears", s: "She was on the brink of tears." },
        { w: "muttered a prayer of thanks", s: "He muttered a prayer of thanks." }
      ],
      "Term 1 Week 9": [
        { w: "Paralympians", s: "We cheered for the Paralympians." },
        { w: "achievements", s: "Be proud of your achievements." },
        { w: "opponent", s: "Shake hands with your opponent." },
        { w: "visually impaired", s: "The book is for the visually impaired." },
        { w: "representatives", s: "They are school representatives." },
        { w: "inclined ramp", s: "Use the inclined ramp." },
        { w: "dilemma", s: "I faced a difficult dilemma." },
        { w: "conscientious", s: "She is a conscientious student." },
        { w: "fish out of water", s: "I felt like a fish out of water." },
        { w: "silent admittance", s: "It was a silent admittance of guilt." },
        { w: "sigh deeply with resignation", s: "He sighed deeply with resignation." },
        { w: "mustered up his courage", s: "He mustered up his courage." }
      ],
      "Term 2 Week 1": [
        { w: "action", s: "Take action now." },
        { w: "amazement", s: "He stared in amazement." },
        { w: "happiness", s: "Money cannot buy happiness." },
        { w: "disability", s: "Do not mock a disability." },
        { w: "cheerfulness", s: "Her cheerfulness is contagious." },
        { w: "decision", s: "It was a hard decision." },
        { w: "destruction", s: "The storm caused destruction." },
        { w: "emptiness", s: "He felt a sense of emptiness." },
        { w: "discussion", s: "We had a long discussion." },
        { w: "responsibility", s: "It is your responsibility." },
        { w: "permission", s: "Ask for permission first." },
        { w: "performance", s: "The performance was great." }
      ],
      "Term 2 Week 2": [
        { w: "extremely", s: "It is extremely hot today." },
        { w: "humour", s: "He has a good sense of humour." },
        { w: "equipment", s: "Pack your sports equipment." },
        { w: "government", s: "The government makes laws." },
        { w: "businessman", s: "The businessman wore a suit." },
        { w: "grievous", s: "He made a grievous error." },
        { w: "embarrass", s: "Do not embarrass me." },
        { w: "shattered into smithereens", s: "The glass shattered into smithereens." },
        { w: "appearance", s: "His sudden appearance scared me." },
        { w: "plummeted through the air", s: "The stone plummeted through the air." },
        { w: "heart could not help but palpitate", s: "My heart could not help but palpitate." },
        { w: "eyes dilated in horror", s: "Her eyes dilated in horror." }
      ],
      "Term 2 Week 3": [
        { w: "annular eclipse", s: "We watched the annular eclipse." },
        { w: "asteroid", s: "An asteroid flew past Earth." },
        { w: "continuously orbit", s: "Planets continuously orbit the sun." },
        { w: "telescope", s: "Look through the telescope." },
        { w: "natural phenomena", s: "Rain is a natural phenomena." },
        { w: "infinitely", s: "Space is infinitely vast." },
        { w: "astronomer", s: "The astronomer studies stars." },
        { w: "mesmerised by the magnificent sunset", s: "We were mesmerised by the magnificent sunset." },
        { w: "stared open-mouthed", s: "He stared open-mouthed at the cake." },
        { w: "eyes blurred with tears of happiness", s: "Her eyes blurred with tears of happiness." },
        { w: "riveted to", s: "I was riveted to the screen." },
        { w: "bleary eyes did their best to focus", s: "His bleary eyes did their best to focus." }
      ],
      "Term 2 Week 4": [
        { w: "miraculously", s: "He miraculously survived." },
        { w: "marvel", s: "We marvel at the view." },
        { w: "commuters", s: "The train was full of commuters." },
        { w: "scenery", s: "The mountain scenery is beautiful." },
        { w: "awe-inspiring", s: "The view was awe-inspiring." },
        { w: "excruciating pain", s: "She was in excruciating pain." },
        { w: "permanent", s: "This marker is permanent." },
        { w: "poisonous", s: "That snake is poisonous." },
        { w: "quarrelled", s: "The brothers quarrelled loudly." },
        { w: "disastrous", s: "The party was disastrous." },
        { w: "souvenir", s: "I bought a souvenir." },
        { w: "separate", s: "Keep the items separate." }
      ],
      "Term 2 Week 5": [
        { w: "hot on his heels", s: "The dog was hot on his heels." },
        { w: "scurried around", s: "The mouse scurried around." },
        { w: "sprang to his feet", s: "He sprang to his feet." },
        { w: "tore down", s: "They tore down the old house." },
        { w: "scuttled off like frightened rats", s: "They scuttled off like frightened rats." },
        { w: "made a mad scramble", s: "We made a mad scramble for the exit." },
        { w: "raced all the way", s: "He raced all the way home." },
        { w: "cried hysterically", s: "The baby cried hysterically." },
        { w: "To her utter dismay", s: "To her utter dismay, it rained." },
        { w: "darted across", s: "The cat darted across the road." },
        { w: "in hot pursuit", s: "The police were in hot pursuit." },
        { w: "fled into the darkness of the alley", s: "The thief fled into the darkness of the alley." }
      ],
      "Term 2 Week 6": [
        { w: "snapped", s: "The twig snapped." },
        { w: "practising", s: "I am practising piano." },
        { w: "measure", s: "Measure the length." },
        { w: "scrambled", s: "He scrambled up the wall." },
        { w: "whispered", s: "She whispered a secret." },
        { w: "stared", s: "He stared at the wall." },
        { w: "filthy", s: "Your shoes are filthy." },
        { w: "warily", s: "He looked around warily." },
        { w: "impetuous", s: "Do not be impetuous." },
        { w: "stealthily", s: "The cat moved stealthily." },
        { w: "dilapidated", s: "The house is dilapidated." },
        { w: "introvert", s: "He is a quiet introvert." }
      ],
      "Term 2 Week 9": [
        { w: "rose in anger", s: "He rose in anger." },
        { w: "hissed through his clenched teeth", s: "She hissed through her clenched teeth." },
        { w: "in a gruff voice", s: "He spoke in a gruff voice." },
        { w: "give him a dressing-down", s: "Mom will give him a dressing-down." },
        { w: "grinned from ear to ear", s: "She grinned from ear to ear." },
        { w: "spoke to me endearingly", s: "Grandma spoke to me endearingly." },
        { w: "made a request with anticipation written all over his face", s: "He made a request with anticipation written all over his face." },
        { w: "with a bone smashing handshake", s: "He greeted me with a bone smashing handshake." },
        { w: "licked his lips nervously", s: "The dog licked his lips nervously." },
        { w: "barely audible", s: "The sound was barely audible." },
        { w: "was oozing with pride", s: "He was oozing with pride." },
        { w: "turned up her nose and snorted", s: "She turned up her nose and snorted." }
      ]
    },
    "zh": {
      "听写(一) (第一课)": [
        { w: "汉语拼音 - 了解 (liǎo jiě)", s: "我了解他的想法。" },
        { w: "汉语拼音 - 秘密 (mì mì)", s: "这是一个秘密。" },
        { w: "汉语拼音 - 情况 (qíng kuàng)", s: "现在情况紧急。" },
        { w: "汉语拼音 - 疲倦 (pí juàn)", s: "他感到很疲倦。" },
        { w: "广告", s: "电视上有个新广告。" },
        { w: "听众", s: "听众们都很安静。" },
        { w: "看新闻", s: "爸爸每晚看新闻。" },
        { w: "一部戏", s: "这是一部精彩的戏。" },
        { w: "看得入迷", s: "他看书看得入迷。" },
        { w: "拍手欢笑", s: "大家拍手欢笑。" },
        { w: "精彩的节目", s: "这是一个精彩的节目。" },
        { w: "国内外的事情", s: "他关心国内外的事情。" },
        { w: "她刚做完了功课。", s: "她刚做完了功课。" },
        { w: "工人叔叔在建房子。", s: "工人叔叔在建房子。" }
      ],
      "听写(二) (第二课)": [
        { w: "汉语拼音 - 递 (dì)", s: "请把书递给我。" },
        { w: "汉语拼音 - 担心 (dān xīn)", s: "妈妈很担心我。" },
        { w: "汉语拼音 - 撑伞 (chēng sǎn)", s: "下雨了，快撑伞。" },
        { w: "汉语拼音 - 表示 (biǎo shì)", s: "他点头表示同意。" },
        { w: "讨论", s: "我们讨论这个问题。" },
        { w: "姑姑", s: "姑姑来看我们了。" },
        { w: "鱼丸面", s: "我想吃鱼丸面。" },
        { w: "兄弟俩", s: "兄弟俩一起上学。" },
        { w: "灵机一动", s: "他灵机一动，想到了办法。" },
        { w: "急急忙忙", s: "他急急忙忙地跑了。" },
        { w: "满天乌云", s: "天上满天乌云。" },
        { w: "又急又怕", s: "我感到又急又怕。" },
        { w: "一串牛肉丸", s: "这是一串牛肉丸。" },
        { w: "忽然下起大雨", s: "忽然下起大雨。" }
      ],
      "听写(三) (第三课)": [
        { w: "汉语拼音 - 批评 (pī píng)", s: "老师批评了他。" },
        { w: "汉语拼音 - 长辈 (zhǎng bèi)", s: "我们要尊敬长辈。" },
        { w: "汉语拼音 - 警察 (jǐng chá)", s: "警察叔叔在抓坏人。" },
        { w: "汉语拼音 - 发脾气 (fā pí qì)", s: "不要随便发脾气。" },
        { w: "最近", s: "最近天气很热。" },
        { w: "偷东西", s: "偷东西是不对的。" },
        { w: "谢谢您", s: "老师，谢谢您。" },
        { w: "华文补习", s: "我去上华文补习。" },
        { w: "迷上游戏", s: "他迷上了电脑游戏。" },
        { w: "尊敬老师", s: "我们要尊敬老师。" },
        { w: "非常后悔", s: "他感到非常后悔。" },
        { w: "一直吵架", s: "他们一直吵架。" },
        { w: "我受不了了。", s: "太吵了，我受不了了。" },
        { w: "不停地流眼泪", s: "他伤心地不停地流眼泪。" }
      ],
      "听写(四) (第四课)": [
        { w: "汉语拼音 - 劝告 (quàn gào)", s: "请听从老师的劝告。" },
        { w: "汉语拼音 - 赞许 (zàn xǔ)", s: "爸爸投来赞许的目光。" },
        { w: "汉语拼音 - 保证 (bǎo zhèng)", s: "我保证不再迟到。" },
        { w: "汉语拼音 - 皱眉头 (zhòu méi tóu)", s: "他生气地皱眉头。" },
        { w: "由于", s: "由于下雨，比赛取消了。" },
        { w: "脚尖", s: "他踮起脚尖走路。" },
        { w: "洗干净", s: "把手洗干净。" },
        { w: "责任重大", s: "班长的责任重大。" },
        { w: "学校食堂", s: "我们在学校食堂吃饭。" },
        { w: "安静地看书", s: "同学们安静地看书。" },
        { w: "你不应该插队。", s: "你不应该插队。" },
        { w: "对别人不公平", s: "这样做对别人不公平。" },
        { w: "今天我负责扫地。", s: "今天我负责扫地。" },
        { w: "注意自己的行为", s: "请注意自己的行为。" }
      ],
      "听写(五) (第五课)": [
        { w: "汉语拼音 - 继续 (jì xù)", s: "休息后继续工作。" },
        { w: "汉语拼音 - 胆小 (dǎn xiǎo)", s: "他很胆小，不敢去。" },
        { w: "汉语拼音 - 微笑 (wēi xiào)", s: "她脸上带着微笑。" },
        { w: "汉语拼音 - 项目 (xiàng mù)", s: "这是个新项目。" },
        { w: "打针", s: "生病了要打针。" },
        { w: "伸出左手", s: "请伸出左手。" },
        { w: "哇哇大哭", s: "弟弟哇哇大哭。" },
        { w: "闷闷不乐", s: "他看起来闷闷不乐。" },
        { w: "回到课室", s: "同学们回到课室。" },
        { w: "定时吃药", s: "要记得定时吃药。" },
        { w: "检查身体", s: "医生帮我检查身体。" },
        { w: "闭起眼睛", s: "闭起眼睛休息一下。" },
        { w: "松了一口气", s: "听了好消息，我松了一口气。" },
        { w: "考试结束了", s: "考试结束了，我很开心。" }
      ],
      "听写(六) (第六课)": [
        { w: "汉语拼音 - 训练 (xùn liàn)", s: "运动员正在训练。" },
        { w: "汉语拼音 - 鼓励 (gǔ lì)", s: "老师鼓励我努力学习。" },
        { w: "汉语拼音 - 丰富 (fēng fù)", s: "这顿晚餐很丰富。" },
        { w: "汉语拼音 - 坚持 (jiān chí)", s: "我们要坚持到底。" },
        { w: "童子军", s: "哥哥是童子军。" },
        { w: "打功夫", s: "他在公园打功夫。" },
        { w: "天天练习", s: "他天天练习写字。" },
        { w: "团队合作", s: "我们需要团队合作。" },
        { w: "身体健康", s: "祝你身体健康。" },
        { w: "好久不见", s: "好久不见，你好吗？" },
        { w: "十分辛苦", s: "妈妈工作十分辛苦。" },
        { w: "游戏开始了", s: "游戏开始了！" },
        { w: "夸我懂事了", s: "妈妈夸我懂事了。" },
        { w: "认识新同学", s: "我认识了新同学。" }
      ],
      "听写(七) (第七课)": [
        { w: "汉语拼音 - 随手 (suí shǒu)", s: "请随手关门。" },
        { w: "汉语拼音 - 道歉 (dào qiàn)", s: "做错了事要道歉。" },
        { w: "汉语拼音 - 秩序 (zhì xù)", s: "请维持秩序。" },
        { w: "汉语拼音 - 耐心 (nài xīn)", s: "我们要有耐心。" },
        { w: "图书馆", s: "我在图书馆看书。" },
        { w: "摇摇头", s: "他无奈地摇摇头。" },
        { w: "听从劝告", s: "我们要听从劝告。" },
        { w: "觉得后悔", s: "他觉得很后悔。" },
        { w: "走进车厢", s: "我们走进车厢。" },
        { w: "拼命地挤", s: "大家拼命地挤上车。" },
        { w: "两位乘客", s: "这里有两位乘客。" },
        { w: "乱抢食物", s: "不要乱抢食物。" },
        { w: "很不好意思", s: "我很不好意思麻烦你。" },
        { w: "排成一条长长的人龙", s: "队伍排成一条长长的人龙。" }
      ],
      "听写(八) (第八课)": [
        { w: "汉语拼音 - 危险 (wēi xiǎn)", s: "马路上很危险。" },
        { w: "汉语拼音 - 遵守 (zūn shǒu)", s: "我们要遵守规则。" },
        { w: "汉语拼音 - 到达 (dào dá)", s: "火车到达了车站。" },
        { w: "汉语拼音 - 采访 (cǎi fǎng)", s: "记者正在采访。" },
        { w: "流血", s: "他的伤口流血了。" },
        { w: "送往医院", s: "伤者被送往医院。" },
        { w: "救护人员", s: "救护人员来了。" },
        { w: "照顾伤者", s: "护士照顾伤者。" },
        { w: "校车司机", s: "校车司机开车很小心。" },
        { w: "交通意外", s: "这里发生了交通意外。" },
        { w: "另一个行人", s: "另一个行人也停下了。" },
        { w: "被困在车里", s: "他被困在车里。" },
        { w: "受了皮外伤", s: "他只受了皮外伤。" },
        { w: "打求救电话", s: "快打求救电话。" }
      ],
      "听写(九) (第九课)": [
        { w: "汉语拼音 - 提供 (tí gōng)", s: "学校提供午餐。" },
        { w: "汉语拼音 - 依然 (yī rán)", s: "他依然那么努力。" },
        { w: "汉语拼音 - 讨厌 (tǎo yàn)", s: "我讨厌吃苦瓜。" },
        { w: "汉语拼音 - 一般 (yì bān)", s: "这个味道很一般。" },
        { w: "文具店", s: "我去文具店买笔。" },
        { w: "组屋居民", s: "组屋居民都很友善。" },
        { w: "地铁月台", s: "我们在地铁月台等车。" },
        { w: "沿着坡道", s: "沿着坡道走上去。" },
        { w: "没听清楚", s: "对不起，我没听清楚。" },
        { w: "离开家人", s: "他不想离开家人。" },
        { w: "其中一个", s: "这是其中一个原因。" },
        { w: "口味变了", s: "他的口味变了。" },
        { w: "笑着用手比画", s: "他笑着用手比画着。" },
        { w: "把座位让给老爷爷", s: "我把座位让给老爷爷。" }
      ]
    }
  },
  "Maddie": {
    "en": {
      "Term 1 Week 5": [
        { w: "rat", s: "The rat ran away." },
        { w: "run", s: "I like to run fast." },
        { w: "cry", s: "Do not cry." },
        { w: "crane", s: "A crane is a tall bird." },
        { w: "fly", s: "Birds fly in the sky." },
        { w: "flowers", s: "The flowers are pretty." },
        { w: "try", s: "Try your best." },
        { w: "tree", s: "The tree is tall." },
        { w: "the", s: "The cat is sleeping." },
        { w: "they", s: "They are my friends." }
      ],
      "Term 1 Week 6": [
        { w: "rain", s: "I like the rain." },
        { w: "train", s: "The train is fast." },
        { w: "mouse", s: "The mouse is small." },
        { w: "house", s: "This is my house." },
        { w: "cake", s: "I love chocolate cake." },
        { w: "face", s: "Wash your face." },
        { w: "ask", s: "Ask a question." },
        { w: "all", s: "We ate all the food." },
        { w: "and", s: "You and I." },
        { w: "you", s: "How are you?" }
      ],
      "Term 1 Week 7": [
        { w: "dug", s: "The dog dug a hole." },
        { w: "duck", s: "The duck says quack." },
        { w: "tap", s: "Turn off the tap." },
        { w: "tub", s: "The tub is full of water." },
        { w: "pig", s: "The pig is pink." },
        { w: "pet", s: "I have a pet dog." },
        { w: "mud", s: "Do not play in the mud." },
        { w: "scrub", s: "Scrub your hands clean." },
        { w: "he", s: "He is my brother." },
        { w: "she", s: "She is my sister." }
      ],
      "Term 1 Week 8": [
        { w: "roll", s: "Roll the ball." },
        { w: "doll", s: "She plays with her doll." },
        { w: "good", s: "You did a good job." },
        { w: "give", s: "Give me the book." },
        { w: "ball", s: "Kick the ball." },
        { w: "bird", s: "The bird sings." },
        { w: "at", s: "Look at me." },
        { w: "that", s: "That is my bag." },
        { w: "in", s: "The cat is in the box." },
        { w: "it", s: "It is a sunny day." }
      ],
      "Term 1 Week 9": [
        { w: "lion", s: "The lion roars." },
        { w: "lick", s: "Dogs lick their paws." },
        { w: "not", s: "I am not hungry." },
        { w: "note", s: "Write a note." },
        { w: "walk", s: "We walk to school." },
        { w: "water", s: "Drink more water." },
        { w: "snap", s: "Snap your fingers." },
        { w: "snake", s: "The snake hisses." },
        { w: "be", s: "Be happy." },
        { w: "his", s: "This is his pen." }
      ],
      "Term 1 Week 10": [
        { w: "cap", s: "Put on your cap." },
        { w: "trap", s: "The mouse is in the trap." },
        { w: "tea", s: "I like hot tea." },
        { w: "leap", s: "Frogs leap high." },
        { w: "feel", s: "I feel happy." },
        { w: "see", s: "I see a bird." },
        { w: "sweet", s: "Candy is sweet." },
        { w: "swing", s: "Play on the swing." },
        { w: "for", s: "This gift is for you." },
        { w: "what", s: "What is your name?" }
      ],
      "Term 2 Week 1": [
        { w: "late", s: "Do not be late." },
        { w: "gate", s: "Close the gate." },
        { w: "five", s: "I have five fingers." },
        { w: "hive", s: "Bees live in a hive." },
        { w: "sticks", s: "Pick up the sticks." },
        { w: "stop", s: "Stop the car." },
        { w: "tiger", s: "The tiger has stripes." },
        { w: "open", s: "Open the door." },
        { w: "out", s: "Go out and play." },
        { w: "come", s: "Come here please." }
      ],
      "Term 2 Week 2": [
        { w: "walked", s: "We walked home." },
        { w: "jumped", s: "The frog jumped." },
        { w: "bug", s: "There is a bug." },
        { w: "jug", s: "Pour water from the jug." },
        { w: "pop", s: "The balloon went pop." },
        { w: "mop", s: "Mop the floor." },
        { w: "pie", s: "I like apple pie." },
        { w: "tie", s: "Tie your shoelaces." },
        { w: "so", s: "I am so happy." },
        { w: "up", s: "Look up at the sky." }
      ],
      "Term 2 Week 3": [
        { w: "giant", s: "The giant is tall." },
        { w: "gentle", s: "Be gentle with the baby." },
        { w: "zoom", s: "Cars zoom by." },
        { w: "food", s: "Eat your food." },
        { w: "bread", s: "I eat bread for breakfast." },
        { w: "break", s: "Do not break the glass." },
        { w: "blew", s: "The wind blew hard." },
        { w: "drew", s: "I drew a picture." },
        { w: "after", s: "Play after school." },
        { w: "with", s: "Come with me." }
      ],
      "Term 2 Week 4": [
        { w: "goat", s: "The goat eats grass." },
        { w: "game", s: "Let's play a game." },
        { w: "glue", s: "Use glue to stick it." },
        { w: "blue", s: "The sky is blue." },
        { w: "grass", s: "The grass is green." },
        { w: "grab", s: "Grab the ball." },
        { w: "tooth", s: "My tooth fell out." },
        { w: "soon", s: "See you soon." },
        { w: "get", s: "Get ready for bed." },
        { w: "some", s: "I want some water." }
      ],
      "Term 2 Week 5": [
        { w: "push", s: "Push the door open." },
        { w: "flush", s: "Flush the toilet." },
        { w: "out", s: "Get out of bed." },
        { w: "mouth", s: "Open your mouth." },
        { w: "down", s: "Sit down please." },
        { w: "clown", s: "The clown is funny." },
        { w: "dark", s: "It is dark at night." },
        { w: "star", s: "Look at the star." },
        { w: "these", s: "These are my shoes." },
        { w: "them", s: "Give them the ball." }
      ],
      "Term 2 Week 6": [
        { w: "scurry", s: "Mice scurry away." },
        { w: "hurry", s: "Hurry up, we are late." },
        { w: "queen", s: "The queen wears a crown." },
        { w: "honey", s: "Bees make honey." },
        { w: "nibble", s: "Mice nibble cheese." },
        { w: "bubble", s: "Pop the bubble." },
        { w: "drink", s: "Drink your milk." },
        { w: "drive", s: "Dad can drive a car." },
        { w: "more", s: "I want more cake." },
        { w: "are", s: "We are happy." }
      ],
      "Term 2 Week 7": [
        { w: "fridge", s: "The milk is in the fridge." },
        { w: "flat", s: "The tire is flat." },
        { w: "creep", s: "Spiders creep." },
        { w: "crawl", s: "Babies crawl." },
        { w: "plan", s: "We have a plan." },
        { w: "stroll", s: "We went for a stroll." },
        { w: "glad", s: "I am glad to see you." },
        { w: "find", s: "Find the hidden toy." },
        { w: "has", s: "She has a cat." },
        { w: "ask", s: "Ask for help." }
      ],
      "Term 2 Week 8": [
        { w: "shelf", s: "Put the book on the shelf." },
        { w: "chair", s: "Sit on the chair." },
        { w: "march", s: "Soldiers march together." },
        { w: "fish", s: "Fish swim in the sea." },
        { w: "skip", s: "Skip down the road." },
        { w: "quick", s: "Be quick!" },
        { w: "trick", s: "It was a magic trick." },
        { w: "have", s: "I have a pen." },
        { w: "look", s: "Look at the bird." },
        { w: "little", s: "The kitten is little." }
      ],
      "Term 3 Week 1": [
        { w: "dress", s: "She wore a red dress." },
        { w: "press", s: "Press the button." },
        { w: "castle", s: "The king lives in a castle." },
        { w: "listen", s: "Listen to the music." },
        { w: "brother", s: "He is my brother." },
        { w: "father", s: "My father is at work." },
        { w: "mother", s: "I love my mother." },
        { w: "sister", s: "My sister plays with me." },
        { w: "They like to read books about animals.", s: "They like to read books about animals." },
        { w: "Susan did her homework neatly.", s: "Susan did her homework neatly." }
      ],
      "Term 3 Week 2": [
        { w: "less", s: "Five is less than ten." },
        { w: "miss", s: "I miss you." },
        { w: "whistle", s: "He can whistle a tune." },
        { w: "often", s: "I often go to the park." },
        { w: "boast", s: "Do not boast about winning." },
        { w: "burst", s: "The balloon burst." },
        { w: "enjoy", s: "Enjoy your meal." },
        { w: "annoy", s: "Do not annoy the cat." },
        { w: "The shop was closed when we arrived.", s: "The shop was closed when we arrived." },
        { w: "We were so happy to go on a holiday.", s: "We were so happy to go on a holiday." }
      ],
      "Term 3 Week 3": [
        { w: "glass", s: "Drink a glass of water." },
        { w: "fuss", s: "Do not make a fuss." },
        { w: "soften", s: "Butter softens in heat." },
        { w: "fasten", s: "Fasten your seatbelt." },
        { w: "cousin", s: "My cousin is visiting." },
        { w: "grandfather", s: "Grandfather tells stories." },
        { w: "grandmother", s: "Grandmother bakes cookies." },
        { w: "uncle", s: "My uncle is tall." },
        { w: "I buy a birthday present for my aunt.", s: "I buy a birthday present for my aunt." },
        { w: "The baby cries when he is hungry.", s: "The baby cries when he is hungry." }
      ],
      "Term 3 Week 4": [
        { w: "problem", s: "Solve the math problem." },
        { w: "please", s: "Say please." },
        { w: "where", s: "Where are you?" },
        { w: "who", s: "Who is that?" },
        { w: "tall", s: "The tree is tall." },
        { w: "talk", s: "Let's talk." },
        { w: "mooncake", s: "I like mooncake." },
        { w: "lantern", s: "Light the lantern." },
        { w: "I cannot find my wallet anywhere.", s: "I cannot find my wallet anywhere." },
        { w: "Dan sees him buying fruits at the stall.", s: "Dan sees him buying fruits at the stall." }
      ],
      "Term 3 Week 5": [
        { w: "stool", s: "Sit on the stool." },
        { w: "street", s: "Look both ways crossing the street." },
        { w: "which", s: "Which one do you want?" },
        { w: "why", s: "Why is the sky blue?" },
        { w: "bald", s: "The man is bald." },
        { w: "salt", s: "Pass the salt." },
        { w: "dumplings", s: "I love dumplings." },
        { w: "festival", s: "We celebrated the festival." },
        { w: "I enjoy the food of other races.", s: "I enjoy the food of other races." },
        { w: "May I go to the party with my friends?", s: "May I go to the party with my friends?" }
      ],
      "Term 3 Week 6": [
        { w: "want", s: "I want a cookie." },
        { w: "front", s: "Sit in the front." },
        { w: "when", s: "When are we going?" },
        { w: "white", s: "Snow is white." },
        { w: "call", s: "Call me later." },
        { w: "stall", s: "The food stall is open." },
        { w: "people", s: "Many people are here." },
        { w: "delicious", s: "The cake is delicious." },
        { w: "The sun is going down behind the mountains.", s: "The sun is going down behind the mountains." },
        { w: "May I borrow this book?", s: "May I borrow this book?" }
      ],
      "Term 3 Week 7": [
        { w: "pockets", s: "I have pockets in my pants." },
        { w: "packets", s: "Two packets of chips." },
        { w: "drain", s: "Water goes down the drain." },
        { w: "draw", s: "I like to draw." },
        { w: "kisses", s: "Mom gives me kisses." },
        { w: "buses", s: "The buses are red." },
        { w: "shirt", s: "Wear a clean shirt." },
        { w: "third", s: "He came in third place." },
        { w: "I put my lunchbox into my school bag.", s: "I put my lunchbox into my school bag." },
        { w: "Paul has never been to the library.", s: "Paul has never been to the library." }
      ],
      "Term 3 Week 8": [
        { w: "kneels", s: "He kneels down." },
        { w: "knock", s: "Knock on the door." },
        { w: "tart", s: "I ate a lemon tart." },
        { w: "hard", s: "The rock is hard." },
        { w: "floor", s: "Sweep the floor." },
        { w: "door", s: "Open the door." },
        { w: "breakfast", s: "Eat your breakfast." },
        { w: "sorry", s: "Say sorry." },
        { w: "I can see many animals at the zoo.", s: "I can see many animals at the zoo." },
        { w: "Please complete this worksheet now.", s: "Please complete this worksheet now." }
      ],
      "Term 3 Week 9": [
        { w: "naughty", s: "The naughty puppy chewed my shoe." },
        { w: "hungry", s: "I am hungry." },
        { w: "nurse", s: "The nurse helps sick people." },
        { w: "purple", s: "Grapes are purple." },
        { w: "clothes", s: "Fold your clothes." },
        { w: "dressed", s: "Get dressed for school." },
        { w: "after", s: "After lunch, we play." },
        { w: "letter", s: "Write a letter." },
        { w: "The children wash their plates after dinner.", s: "The children wash their plates after dinner." },
        { w: "He gives his grandchildren green packets.", s: "He gives his grandchildren green packets." }
      ],
      "Term 4 Week 1": [
        { w: "scratch", s: "Do not scratch the itch." },
        { w: "scrapes", s: "He scrapes his knee." },
        { w: "hatch", s: "The eggs will hatch." },
        { w: "watch", s: "Watch the movie." },
        { w: "boat", s: "The boat floats." },
        { w: "coat", s: "Wear a warm coat." },
        { w: "worked", s: "He worked hard." },
        { w: "The tiger prowled through the jungle.", s: "The tiger prowled through the jungle." },
        { w: "The farmyard is filled with animals.", s: "The farmyard is filled with animals." },
        { w: "The ducks waddled happily to the pond.", s: "The ducks waddled happily to the pond." }
      ],
      "Term 4 Week 2": [
        { w: "screen", s: "Look at the screen." },
        { w: "scramble", s: "Scramble the eggs." },
        { w: "match", s: "Light a match." },
        { w: "snatch", s: "Do not snatch toys." },
        { w: "float", s: "Boats float on water." },
        { w: "throat", s: "My throat hurts." },
        { w: "sheep", s: "Sheep have wool." },
        { w: "The gardener pulls out all the weeds.", s: "The gardener pulls out all the weeds." },
        { w: "The lazy boy does nothing the whole day.", s: "The lazy boy does nothing the whole day." },
        { w: "The farmers milk their cows in the morning.", s: "The farmers milk their cows in the morning." }
      ],
      "Term 4 Week 3": [
        { w: "screams", s: "She screams loudly." },
        { w: "scribbles", s: "He scribbles on paper." },
        { w: "patch", s: "Sew a patch on the pants." },
        { w: "fetch", s: "Fetch the ball." },
        { w: "loaf", s: "A loaf of bread." },
        { w: "goal", s: "Score a goal." },
        { w: "bottle", s: "Drink from the bottle." },
        { w: "I put the beetle in a jar.", s: "I put the beetle in a jar." },
        { w: "The animals live on the farm.", s: "The animals live on the farm." },
        { w: "There are colourful flowers in the garden.", s: "There are colourful flowers in the garden." }
      ],
      "Term 4 Week 4": [
        { w: "play", s: "Let's play outside." },
        { w: "away", s: "Go away." },
        { w: "tray", s: "Put the food on a tray." },
        { w: "team", s: "We are a good team." },
        { w: "mean", s: "Do not be mean." },
        { w: "beach", s: "We built sandcastles at the beach." },
        { w: "head", s: "Wear a hat on your head." },
        { w: "We spread some butter on our slice of bread.", s: "We spread some butter on our slice of bread." },
        { w: "Grandma keeps her needle and thread in her sewing box.", s: "Grandma keeps her needle and thread in her sewing box." },
        { w: "There are seven candles on my cake.", s: "There are seven candles on my cake." }
      ],
      "Term 4 Week 5": [
        { w: "rain", s: "The rain falls down." },
        { w: "mail", s: "Check the mail." },
        { w: "snail", s: "The snail is slow." },
        { w: "sleep", s: "Go to sleep." },
        { w: "feet", s: "Stomp your feet." },
        { w: "teeth", s: "Brush your teeth." },
        { w: "off", s: "Turn off the light." },
        { w: "Dogs sniff their food before eating.", s: "Dogs sniff their food before eating." },
        { w: "I feel a puff of air against my cheeks.", s: "I feel a puff of air against my cheeks." },
        { w: "I celebrate my birthday at home.", s: "I celebrate my birthday at home." }
      ],
      "Term 4 Week 6": [
        { w: "bake", s: "Bake a cake." },
        { w: "paper", s: "Write on paper." },
        { w: "lady", s: "The lady is kind." },
        { w: "field", s: "Run in the field." },
        { w: "thief", s: "The thief stole the bag." },
        { w: "piece", s: "Have a piece of cake." },
        { w: "quiet", s: "Be quiet in the library." },
        { w: "I was quite sad when I did not win the prize.", s: "I was quite sad when I did not win the prize." },
        { w: "The ducks quack loudly at the farmer.", s: "The ducks quack loudly at the farmer." },
        { w: "The gardener trims the trees.", s: "The gardener trims the trees." }
      ],
      "Term 4 Week 7": [
        { w: "jolly", s: "Santa is jolly." },
        { w: "jelly", s: "I like jelly." },
        { w: "smiled", s: "She smiled at me." },
        { w: "smelly", s: "The trash is smelly." },
        { w: "thank", s: "Say thank you." },
        { w: "bank", s: "Save money in the bank." },
        { w: "fast", s: "Run fast." },
        { w: "Mary makes a list of things she needs to bring.", s: "Mary makes a list of things she needs to bring." },
        { w: "Grandma is sad when she sees her broken vase.", s: "Grandma is sad when she sees her broken vase." },
        { w: "Sam receives a present from his uncle.", s: "Sam receives a present from his uncle." }
      ],
      "Term 4 Week 8": [
        { w: "juice", s: "Drink orange juice." },
        { w: "jokes", s: "Tell funny jokes." },
        { w: "smoke", s: "Smoke is bad for you." },
        { w: "smash", s: "Do not smash the toy." },
        { w: "trunk", s: "The elephant has a trunk." },
        { w: "think", s: "Think before you speak." },
        { w: "test", s: "Good luck on your test." },
        { w: "Peter has the best handwriting in class.", s: "Peter has the best handwriting in class." },
        { w: "Rita puts the gold bangle into her bag.", s: "Rita puts the gold bangle into her bag." },
        { w: "The dustbin is placed outside our class.", s: "The dustbin is placed outside our class." }
      ]
    },
    "zh": {
      "听写(一/二) (第一/二课)": [
        { w: "汉语拼音 - 大雨 (dà yǔ)", s: "外面下着大雨。" },
        { w: "汉语拼音 - 马路 (mǎ lù)", s: "过马路要小心。" },
        { w: "汉语拼音 - 乌鸦 (wū yā)", s: "乌鸦是黑色的。" },
        { w: "汉语拼音 - 女儿 (nǚ ér)", s: "她是我的女儿。" },
        { w: "汉语拼音 - 衣服 (yī fu)", s: "这件衣服很漂亮。" },
        { w: "五", s: "我有五个苹果。" },
        { w: "口", s: "张开你的口。" },
        { w: "人", s: "这里有很多人。" },
        { w: "木", s: "这是木头做的。" },
        { w: "土", s: "花种在土里。" },
        { w: "八", s: "现在八点了。" },
        { w: "也", s: "我也要去。" },
        { w: "不", s: "我不喜欢吃这个。" },
        { w: "女儿", s: "可爱的女儿。" }
      ],
      "听写三 (第三课)": [
        { w: "汉语拼音 - 举 (jǔ)", s: "举起你的手。" },
        { w: "汉语拼音 - 去 (qù)", s: "我要去上学。" },
        { w: "汉语拼音 - 可以 (kě yǐ)", s: "我可以玩吗？" },
        { w: "汉语拼音 - 狐狸 (hú li)", s: "狐狸很聪明。" },
        { w: "汉语拼音 - 洗衣机 (xǐ yī jī)", s: "妈妈用洗衣机洗衣服。" },
        { w: "汉语拼音 - 哥哥哭了 (gē ge kū le)", s: "哥哥哭了。" },
        { w: "力", s: "我们要出力。" },
        { w: "几", s: "你有几本书？" },
        { w: "七", s: "我有七支笔。" },
        { w: "个", s: "这是一个苹果。" },
        { w: "可", s: "可是我很累。" },
        { w: "去", s: "我们去公园。" },
        { w: "未", s: "未来。" }
      ],
      "听写四 (第四课)": [
        { w: "汉语拼音 - 擦 (cā)", s: "擦黑板。" },
        { w: "汉语拼音 - 热 (rè)", s: "今天很热。" },
        { w: "汉语拼音 - 司机 (sī jī)", s: "司机开车。" },
        { w: "汉语拼音 - 组屋 (zǔ wū)", s: "我们住在组屋。" },
        { w: "汉语拼音 - 十只猪 (shí zhī zhū)", s: "那里有十只猪。" },
        { w: "汉语拼音 - 一把尺 (yì bǎ chǐ)", s: "我有一把尺。" },
        { w: "四", s: "四只小鸟。" },
        { w: "只", s: "一只猫。" },
        { w: "子", s: "儿子。" },
        { w: "十", s: "十个手指。" },
        { w: "日", s: "今日。" },
        { w: "车", s: "汽车。" },
        { w: "巴士", s: "坐巴士。" }
      ],
      "听写五 (第五课)": [
        { w: "汉语拼音 - 老师 (lǎo shī)", s: "老师早安。" },
        { w: "汉语拼音 - 草 (cǎo)", s: "草地是绿的。" },
        { w: "汉语拼音 - 男孩 (nán hái)", s: "那个男孩在跑。" },
        { w: "汉语拼音 - 玩具 (wán jù)", s: "我喜欢玩玩具。" },
        { w: "汉语拼音 - 太阳 (tài yáng)", s: "太阳出来了。" },
        { w: "汉语拼音 - 五把伞 (wǔ bǎ sǎn)", s: "这里有五把伞。" },
        { w: "山羊", s: "山羊在吃草。" },
        { w: "书", s: "我看书。" },
        { w: "王", s: "国王。" },
        { w: "午", s: "中午。" },
        { w: "早", s: "早上好。" },
        { w: "三", s: "三个朋友。" },
        { w: "毛", s: "毛巾。" }
      ],
      "听写六 (第六课)": [
        { w: "汉语拼音 - 借书 (jiè shū)", s: "我去图书馆借书。" },
        { w: "汉语拼音 - 面包 (miàn bāo)", s: "我早餐吃面包。" },
        { w: "汉语拼音 - 跳舞 (tiào wǔ)", s: "妹妹喜欢跳舞。" },
        { w: "汉语拼音 - 香蕉 (xiǎng jiāo)", s: "猴子爱吃香蕉。" },
        { w: "汉语拼音 - 两只小虾 (liǎng zhī xiǎo xiā)", s: "水里有两只小虾。" },
        { w: "田", s: "田地。" },
        { w: "力", s: "力气。" },
        { w: "在", s: "我在家。" },
        { w: "上", s: "上面。" },
        { w: "下", s: "下面。" },
        { w: "大", s: "大苹果。" },
        { w: "小", s: "小猫。" }
      ],
      "听写七 (第七课)": [
        { w: "汉语拼音 - 一朵花 (yì duǒ huā)", s: "这是一朵花。" },
        { w: "汉语拼音 - 关窗 (guān chuāng)", s: "下雨了，请关窗。" },
        { w: "汉语拼音 - 桌子 (zhuō zi)", s: "桌子上有一本书。" },
        { w: "汉语拼音 - 快乐 (kuài lè)", s: "祝你生日快乐。" },
        { w: "汉语拼音 - 图书馆 (tú shū guǎn)", s: "图书馆很安静。" },
        { w: "开", s: "开门。" },
        { w: "大", s: "大家。" },
        { w: "关", s: "关灯。" },
        { w: "两", s: "两个。" },
        { w: "长", s: "长短。" },
        { w: "广", s: "广大。" },
        { w: "多", s: "多少。" }
      ],
      "听写八 (第八课)": [
        { w: "汉语拼音 - 猴子 (hóu zi)", s: "猴子爬树。" },
        { w: "汉语拼音 - 本子 (běn zi)", s: "拿本子出来写字。" },
        { w: "汉语拼音 - 打雷 (dǎ léi)", s: "外面打雷了。" },
        { w: "汉语拼音 - 好朋友 (hǎo péng you)", s: "我们是好朋友。" },
        { w: "汉语拼音 - 七条虫 (qī tiáo chóng)", s: "鸟儿吃了七条虫。" },
        { w: "目", s: "目光。" },
        { w: "手", s: "拍手。" },
        { w: "本", s: "课本。" },
        { w: "工", s: "工人。" },
        { w: "门", s: "大门。" },
        { w: "见", s: "再见。" },
        { w: "又", s: "又来了。" },
        { w: "头", s: "头发。" }
      ],
      "听写九 (第九课)": [
        { w: "汉语拼音 - 打球 (dǎ qiú)", s: "哥哥在打球。" },
        { w: "汉语拼音 - 眼睛 (yǎn jīng)", s: "她的眼睛很大。" },
        { w: "汉语拼音 - 熊猫 (xióng māo)", s: "熊猫吃竹子。" },
        { w: "汉语拼音 - 一颗心 (yì kē xīn)", s: "画一颗心。" },
        { w: "汉语拼音 - 四头牛 (sì tóu niú)", s: "草地上有四头牛。" },
        { w: "牛", s: "水牛。" },
        { w: "贝", s: "贝壳。" },
        { w: "六", s: "六个。" },
        { w: "支", s: "一支笔。" },
        { w: "九", s: "九点。" },
        { w: "什么", s: "这是什么？" },
        { w: "文", s: "华文。" }
      ],
      "听写十 (第十课)": [
        { w: "汉语拼音 - 水果 (shuǐ guǒ)", s: "多吃水果身体好。" },
        { w: "汉语拼音 - 存钱 (cún qián)", s: "我要存钱买书。" },
        { w: "汉语拼音 - 音乐 (yīn yuè)", s: "我喜欢听音乐。" },
        { w: "汉语拼音 - 做运动 (zuò yùn dòng)", s: "我们要常做运动。" },
        { w: "汉语拼音 - 卷笔刀 (juǎn bǐ dāo)", s: "这是我的卷笔刀。" },
        { w: "月", s: "月亮。" },
        { w: "天", s: "天空。" },
        { w: "水", s: "喝水。" },
        { w: "寸", s: "一寸。" },
        { w: "正", s: "正在。" },
        { w: "反", s: "相反。" },
        { w: "白", s: "白色。" },
        { w: "古", s: "古代。" }
      ]
    }
  }
};
